{
    "window.zoomLevel": 0,
    "window.menuBarVisibility": "default",
    "editor.minimap.enabled": true,
    "editor.fontFamily": "Consolas, 'Courier New', monospace",
    "editor.tabSize": 4,
    "editor.wordWrap": "on",
    "workbench.iconTheme": "vscode-icons",
    "vsicons.dontShowNewVersionMessage": true,
    "workbench.activityBar.visible": true,
    "terminal.integrated.shell.linux": "/bin/zsh",
    "terminal.integrated.rendererType": "canvas",
    "terminal.integrated.drawBoldTextInBrightColors": true,
    "terminal.integrated.scrollback": 1000,
    "files.autoSave": "afterDelay",
    "eslint.enable": true,
    "terminal.integrated.fontFamily": "Ubuntu mono",
    "css.lint.hexColorLength": "error",
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "workbench.colorTheme": "Monokai",
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "editor.snippetSuggestions": "top",
    "window.title": "${dirty} ${activeEditorMedium}${separator}${rootName}",
    "editor.cursorStyle": "line-thin",
    "breadcrumbs.enabled": true,
    "editor.selectionClipboard": false,
    "window.titleBarStyle": "custom",
    "editor.smoothScrolling": true,"workbench.panel.defaultLocation": "right",
    "terminal.explorerKind": "external",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "explorer.confirmDragAndDrop": false,
    "reason.path.ocamlmerlin": "/home/michalhonc/.opam/default/bin/ocamlmerlin",
    "postcssSorting.config": {
        "properties-order": ["display","float","position","left","right","top","bottom","order","align-self","z-index","clear","box-sizing","margin","margin-top","margin-right","margin-bottom","margin-left","border","border-top","border-right","border-bottom","border-left","border-radius","padding","padding-top","padding-right","padding-bottom","padding-left","width","min-width","max-width","height","min-height","max-height","flex","flex-grow","flex-shrink","flex-basis","overflow","flex","flex-flow","flex-direction","flex-wrap","justify-content","align-content","align-items","column-count","column-width","column-gap","column-rule","column-fill","column-span","object-position","object-fit","content","text-indent","font","line-height","text-align","vertical-align","color","white-space","text-overflow","text-transform","text-decoration","text-shadow","background","background-color","background-image","background-repeat","background-attachment","background-position","list-style","box-shadow","transform","animation","transition","appearance","cursor","visibility","opacity",],
    },
    "editor.parameterHints.enabled": false,
    "workbench.startupEditor": "newUntitledFile",
    "auto-rename-tag.activationOnLanguage": [
        "html",
        "xml",
        "javascript",
        "javascriptreact",
    ],
    "auto-close-tag.activationOnLanguage": [
        "xml",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "plaintext",
        "markdown",
        "cfml",
        "HTML (Eex)"
    ],
    
}
